#! /bin/sh

#--- install kernel
# TODO : assuming that there's only one kernel
kernel=$(cd /etc/lucie/kernel; ls kernel-image*)
cp /etc/lucie/kernel/$kernel /tmp/target/tmp/
chroot /tmp/target /bin/sh -c '( kernel=$(cd /tmp; ls kernel-image*); echo -e "n\n" | dpkg -i /tmp/$kernel )'

#--- install grub into boot device
cp /tmp/lucie/disk_var.sh /tmp/target/tmp/
chroot /tmp/target /bin/sh -c '(. /tmp/disk_var.sh; mount -f /; /bin/sh grub-install --no-floppy $BOOT_DEVICE)'


#--- create /boot/grub/menu.lst
# load variables concerned with disk
. /tmp/lucie/disk_var.sh

# TODO : assuming that there's only one kernel

vmlinuz=$(cd /tmp/target/boot; ls vmlinuz*)

echo "Creating menu.lst for /vmlinuz"
cat > /tmp/target/boot/grub/menu.lst <<-EOF
default 0
timeout 5
color cyan/blue white/blue

title           Debian
root            (hd0,0)
kernel          /boot/$vmlinuz root=$ROOT_PARTITION ro
EOF

# if the installed kernel is using an initial ramdisk
if [ -e /tmp/target/boot/initrd.img* ]; then
  initrd_img=$(cd /tmp/target/boot; ls initrd.img*)
  cat >> /tmp/target/boot/grub/menu.lst <<-EOF
initrd          /boot/$initrd_img
EOF
fi

cat >> /tmp/target/boot/grub/menu.lst <<-EOF
savedefault
boot

EOF
