#! /bin/sh

# load variables concerned with disk
. /tmp/lucie/disk_var.sh

# add xen kernel into menu.lst
if ! [ -f /tmp/target/boot/grub/menu.lst ]; then
  echo "/boot/grub/menu.lst does not exist."
  echo "Xen kernel will not be booted next time."
  exit 1
fi

echo "Editing menu.lst for /xen"
cat >> /tmp/target/boot/grub/menu.lst <<-EOF

title		Debian (Xen0)
kernel		/boot/xen.gz dom0_mem=%%%MEMORY%%%
module		/boot/vmlinuz-2.6-xen0 root=$ROOT_PARTITION ro console=tty1

EOF

