#!/bin/sh

# /etc/lucie/java 以下にディレクトリは一つと仮定
jre_dir=$(ls /etc/lucie/java/)
mv /etc/lucie/java/$jre_dir /tmp/target/usr/lib/

echo "export JAVA_HOME=/usr/lib/$jre_dir" >> /tmp/target/etc/profile
echo "export PATH=\${JAVA_HOME}/bin:\$PATH" >> /tmp/target/etc/profile
