#! /bin/sh

# (c) Thomas Lange, 2001-2005, lange@debian.org

# disable fsck on ext3 filesystems
partitions=`mount|grep $target |grep "type ext3"|perl -ane 'print "$F[0] "'`
for part in $partitions; do
    echo "Disable periodic fsck on $part"
    tune2fs -c 0 -i 0 $part
done

ln -s /boot/vmlinuz-nolink $target/vmlinuz
fcopy /etc/kernel-img.conf
yes 'n' | dpkg --root=$target -i /etc/lucie/kernel/$kernel_package

fcopy /etc/hostname || echo $HOSTNAME     > $target/etc/hostname
echo $time_zone    > $target/etc/timezone
ln -fs /usr/share/zoneinfo/${time_zone} $target/etc/localtime

fcopy -iM /etc/hosts /etc/motd

# make /root accessable only by root
chmod 0700 $target/root
chown root:root $target/root
# copy default dotfiles for root account
fcopy -r /root

# create keyboard layput table
dumpkeys | gzip -9f >$target/etc/console/boottime.kmap.gz
