#! /bin/bash

# copyright Thomas Lange 2001-2005, lange@debian.org
# LILO support may be dropped in a future release

# use debconf
. /usr/share/debconf/confmodule

db_get lucie-client/default/modules
modules=$RET

echo $modules

# a list of modules which are loaded at boot time
fcopy /etc/modules
for module in ${modules//,/ }; do
    echo $module >> /tmp/target/etc/modules
done
